//! Output Perturbation — add calibrated Gaussian noise to the cursor channel.
//!
//! The noise is integer and table-driven, never floating-point, so it is
//! bit-identical on every platform (a `libm` difference between two nodes would
//! otherwise desync replay/verify). The Gaussian is sampled by indexing a fixed
//! inverse-CDF table with a uniform value — exactly the scheme the on-metal M5
//! plan calls for (RDTSC entropy + Q8.8 inverse-CDF LUT).
//!
//! The uniform itself comes from the NDAL Random oracle (see lib.rs), so the
//! draw is recorded in the replay log: replay reproduces the same noise, a
//! fresh observer cannot predict it.

use crate::table::{CURSOR_DX, CURSOR_DY, OUTPUT_MAX, OUTPUT_MIN, OUTPUT_SIZE, PX_SHIFT};

/// Inverse standard-normal CDF, sampled at u_i = (i + 0.5)/N, in units of
/// 1/1024 σ (Q10). **Normalized so the table's own RMS is exactly 1.0 σ**
/// (emitted-table RMS = 1.000016 σ) — so `noise_output_units` applies the σ the
/// Risk Engine computed, with no systematic under- or over-noising. Monotone
/// and antisymmetric; effective support is ±2738/1024 ≈ ±2.67 σ (the 128-point
/// mid-bucket sampling never reaches the far tails, which is why normalization,
/// not a wide clamp, is what fixes the variance). Generated by
/// `statistics.NormalDist().inv_cdf` then scaled by 1/RMS; baked so the table
/// is byte-identical on every platform (no libm in the noise path).
pub const GAUSS_N: usize = 128;
pub const GAUSS_Q10: [i32; GAUSS_N] = [
    -2738, -2332, -2124, -1977, -1863, -1767, -1685, -1612,
    -1547, -1487, -1432, -1381, -1333, -1287, -1244, -1204,
    -1165, -1127, -1091, -1056, -1023,  -990,  -959,  -928,
     -898,  -869,  -841,  -813,  -785,  -759,  -733,  -707,
     -682,  -657,  -632,  -608,  -584,  -561,  -537,  -514,
     -492,  -469,  -447,  -425,  -403,  -381,  -360,  -339,
     -317,  -296,  -275,  -254,  -234,  -213,  -193,  -172,
     -152,  -131,  -111,   -91,   -71,   -50,   -30,   -10,
       10,    30,    50,    71,    91,   111,   131,   152,
      172,   193,   213,   234,   254,   275,   296,   317,
      339,   360,   381,   403,   425,   447,   469,   492,
      514,   537,   561,   584,   608,   632,   657,   682,
      707,   733,   759,   785,   813,   841,   869,   898,
      928,   959,   990,  1023,  1056,  1091,  1127,  1165,
     1204,  1244,  1287,  1333,  1381,  1432,  1487,  1547,
     1612,  1685,  1767,  1863,  1977,  2124,  2332,  2738,
];

/// Map a uniform u32 to a standard-normal sample in Q10 (1/1024 σ units).
pub fn gaussian_q10(u: u32) -> i32 {
    let idx = ((u as u64 * GAUSS_N as u64) >> 32) as usize;
    GAUSS_Q10[idx]
}

/// Noise in output units for a uniform `u` and a per-channel σ (output units).
/// `q` is in 1/1024 σ, so `noise = q · σ / 1024`. Rounds to nearest (not the
/// arithmetic-shift floor, which biases toward −∞ and would give the noise a
/// small but systematic negative mean given the antisymmetric LUT). Symmetric
/// rounding keeps the noise zero-mean, which the SNR calibration assumes.
pub fn noise_output_units(u: u32, sigma_out: i64) -> i64 {
    let scaled = gaussian_q10(u) as i64 * sigma_out;
    let half = 1i64 << (PX_SHIFT - 1);
    // round half away from zero, symmetrically about 0
    if scaled >= 0 {
        (scaled + half) >> PX_SHIFT
    } else {
        -((-scaled + half) >> PX_SHIFT)
    }
}

/// Add calibrated noise to the cursor channel only (indices 20 and 22); the
/// command logits [0..20] are never touched, so the decoded command is exact.
/// Results are clamped to the valid output range so decode stays well-defined.
pub fn apply(
    outputs: &mut [i32; OUTPUT_SIZE],
    u_dx: u32,
    u_dy: u32,
    sigma_dx: i64,
    sigma_dy: i64,
) {
    let ndx = noise_output_units(u_dx, sigma_dx);
    let ndy = noise_output_units(u_dy, sigma_dy);
    outputs[CURSOR_DX] =
        (outputs[CURSOR_DX] as i64 + ndx).clamp(OUTPUT_MIN as i64, OUTPUT_MAX as i64) as i32;
    outputs[CURSOR_DY] =
        (outputs[CURSOR_DY] as i64 + ndy).clamp(OUTPUT_MIN as i64, OUTPUT_MAX as i64) as i32;
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn lut_is_monotone_and_antisymmetric() {
        for i in 0..GAUSS_N - 1 {
            assert!(GAUSS_Q10[i] <= GAUSS_Q10[i + 1], "not monotone at {i}");
        }
        for i in 0..GAUSS_N {
            assert_eq!(GAUSS_Q10[i], -GAUSS_Q10[GAUSS_N - 1 - i], "not antisymmetric at {i}");
        }
    }

    #[test]
    fn gaussian_index_covers_full_range_without_panic() {
        assert_eq!(gaussian_q10(0), GAUSS_Q10[0]);
        assert_eq!(gaussian_q10(u32::MAX), GAUSS_Q10[GAUSS_N - 1]);
    }

    #[test]
    fn empirical_mean_near_zero_and_std_near_sigma() {
        // Sweep the uniform space; mean ≈ 0, sample std ≈ σ.
        let sigma = 1024i64; // 1.0 px in output units
        let mut sum = 0i64;
        let mut sumsq = 0i128;
        let n = 100_000u32;
        for k in 0..n {
            // spread k across u32 range
            let u = ((k as u64 * (u32::MAX as u64)) / (n as u64)) as u32;
            let noise = noise_output_units(u, sigma);
            sum += noise;
            sumsq += (noise as i128) * (noise as i128);
        }
        let mean = sum as f64 / n as f64;
        let var = sumsq as f64 / n as f64 - mean * mean;
        let std = var.sqrt();
        // Round-to-nearest keeps the mean tight to 0 (no floor bias).
        assert!(mean.abs() < 1.0, "mean {mean} should be ≈0 (zero-mean noise)");
        // LUT is normalized to unit variance, so std should be within ~2% of σ.
        assert!((std - sigma as f64).abs() / (sigma as f64) < 0.02,
                "std {std} should be ≈ σ {sigma}");
    }

    #[test]
    fn command_logits_untouched() {
        let mut out = [0i32; OUTPUT_SIZE];
        for i in 0..20 {
            out[i] = (i as i32) * 100;
        }
        out[CURSOR_DX] = 16384;
        out[CURSOR_DY] = 16384;
        let before = out;
        apply(&mut out, 0xDEADBEEF, 0x12345678, 4096, 4096);
        assert_eq!(out[..20], before[..20], "command channel must be untouched");
        // cursor channel did move
        assert!(out[CURSOR_DX] != before[CURSOR_DX] || out[CURSOR_DY] != before[CURSOR_DY]);
    }
}
